-- TABLAS DE LA ESTRUCTURA DE UN E-COMMERCE 

drop schema if exists TP_MLBENJAMIN ;
create schema if not exists TP_MLBENJAMIN ;
use TP_MLBENJAMIN;

-- Tabla de usuarios
DROP TABLE IF EXISTS USUARIO;
CREATE TABLE IF NOT EXISTS USUARIO(
ID_USER INT AUTO_INCREMENT,
NOMBRE VARCHAR(15) NOT NULL,
APELLIDO VARCHAR(15),
EMAIL VARCHAR(30) NOT NULL,
TELEFONO VARCHAR(15),
CARRITO VARCHAR(30) NOT NULL,
CLAVE VARCHAR(15) NOT NULL NOT NULL,
FECHA TIMESTAMP NOT NULL,
CONSTRAINT PK_ID_USER PRIMARY KEY(ID_USER)
);

-- Tabla de propietarios de productos
DROP TABLE IF EXISTS PRODUCT_OWNER;
CREATE TABLE IF NOT EXISTS PRODUCT_OWNER(
ID_PRODUCT_OWNER INT AUTO_INCREMENT,
NOMBRE VARCHAR(15) NOT NULL,
APELLIDO VARCHAR(15),
EMPRESA VARCHAR(20) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
TELEFONO VARCHAR(15),
CLAVE VARCHAR(15) NOT NULL,
FECHA TIMESTAMP NOT NULL,
CONSTRAINT PK_PRODUCT_OWNER PRIMARY KEY(ID_PRODUCT_OWNER)
);

-- Tabla de categorías de productos
DROP TABLE IF EXISTS CATEGORIA;
CREATE TABLE IF NOT EXISTS CATEGORIA(
    ID_CATEGORIA INT AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(255),
    CONSTRAINT PK_CATEGORIA_PRODUCTO PRIMARY KEY(ID_CATEGORIA)
);

-- Tabla de productos
DROP TABLE IF EXISTS PRODUCTO;
CREATE TABLE IF NOT EXISTS PRODUCTO(
ID_PRODUCTO INT AUTO_INCREMENT,
NOMBRE_PRODUCTO VARCHAR(15) NOT NULL,
DESCRIPCION VARCHAR(50),
STOCK INT UNSIGNED NOT NULL,
THUMBNAIL VARCHAR(50),
PRECIO INT UNSIGNED,
DUENO_PRODUCTO INT NOT NULL, 
ID_CATEGORIA INT,
CONSTRAINT PK_PRODUCTO PRIMARY KEY(ID_PRODUCTO, NOMBRE_PRODUCTO),
CONSTRAINT FK_DUENO_PRODUCTO FOREIGN KEY(DUENO_PRODUCTO)
	REFERENCES PRODUCT_OWNER(ID_PRODUCT_OWNER),
CONSTRAINT FK_CATEGORIA FOREIGN KEY(ID_CATEGORIA)
	REFERENCES CATEGORIA(ID_CATEGORIA)
);

-- Tabla de carritos
DROP TABLE IF EXISTS CART;
CREATE TABLE IF NOT EXISTS CART(
ID_CART INT AUTO_INCREMENT,
ID_PRODUCTO INT NOT NULL,
CANTIDAD INT UNSIGNED,
NOMBRE_PRODUCTO VARCHAR(20) NOT NULL,
DUENO_CARRITO INT,
FECHA TIMESTAMP NOT NULL,
CONSTRAINT PK_CART PRIMARY KEY(ID_CART),
CONSTRAINT FK_DUENO_CARRITO_CART FOREIGN KEY(DUENO_CARRITO)
	REFERENCES USUARIO(ID_USER),
CONSTRAINT FK_ID_PRODUCTO FOREIGN KEY(ID_PRODUCTO)
        REFERENCES PRODUCTO(ID_PRODUCTO)
);

-- Tabla de chat
DROP TABLE IF EXISTS CHAT;
CREATE TABLE IF NOT EXISTS CHAT(
ID_CHAT INT AUTO_INCREMENT,
USER_ID INT NOT NULL,
MENSAJES VARCHAR (50),
ID_RECEPTOR INT NOT NULL,
CONSTRAINT PK_CHAT PRIMARY KEY(ID_CHAT),
CONSTRAINT FK_USER_ID FOREIGN KEY(USER_ID)
	REFERENCES USUARIO(ID_USER),
CONSTRAINT FK_RECEPTOR FOREIGN KEY(ID_RECEPTOR)
	REFERENCES PRODUCT_OWNER(ID_PRODUCT_OWNER)
);

-- Tabla de tickets de compra
DROP TABLE IF EXISTS TICKET_COMPRA;
CREATE TABLE IF NOT EXISTS TICKET_COMPRA(
ID_TICKET_COMPRA INT AUTO_INCREMENT,
CARRITO INT NOT NULL,
DUENO_CARRITO INT NOT NULL,
FECHA TIMESTAMP NOT NULL,
CONSTRAINT PK_ID_TICKET_COMPRA PRIMARY KEY(ID_TICKET_COMPRA),
CONSTRAINT FK_CARRITO_TICKET FOREIGN KEY(CARRITO)
	REFERENCES CART(ID_CART),
CONSTRAINT FK_DUENO_CARRITO_TICKET FOREIGN KEY(DUENO_CARRITO)
	REFERENCES USUARIO(ID_USER)
);

-- Tabla de órdenes
DROP TABLE IF EXISTS ORDEN;
CREATE TABLE IF NOT EXISTS ORDEN(
    ID_ORDEN INT AUTO_INCREMENT,
    ID_USER INT NOT NULL,
    FECHA TIMESTAMP NOT NULL,
    TOTAL DECIMAL(10, 2) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL,
    CONSTRAINT PK_ORDEN PRIMARY KEY(ID_ORDEN),
    CONSTRAINT FK_ORDEN_USER FOREIGN KEY(ID_USER)
        REFERENCES USUARIO(ID_USER)
);




-- Detalles de la orden
DROP TABLE IF EXISTS ORDEN_DETALLE;
CREATE TABLE IF NOT EXISTS ORDEN_DETALLE(
    ID_ORDEN_DETALLE INT AUTO_INCREMENT,
    ID_ORDEN INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT UNSIGNED NOT NULL,
    PRECIO_UNITARIO DECIMAL(10, 2) NOT NULL,
    CONSTRAINT PK_ORDEN_DETALLE PRIMARY KEY(ID_ORDEN_DETALLE),
    CONSTRAINT FK_ORDEN FOREIGN KEY(ID_ORDEN)
        REFERENCES ORDEN(ID_ORDEN),
    CONSTRAINT FK_PRODUCTO FOREIGN KEY(ID_PRODUCTO)
        REFERENCES PRODUCTO(ID_PRODUCTO)
);