-- TRIGGERS
-- Tabla a la que se le crea el trigger
SELECT * FROM PRODUCTO;

-- Tabla donde se guarada el resultado del trigger
drop table if  exists AUDIT_PRODUCTO;
CREATE TABLE IF NOT EXISTS AUDIT_PRODUCTO
(
ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_DE_ACCION VARCHAR(10) ,
NOMBRE_TABLA VARCHAR(50) ,
ID_PRODUCTO INT,
USUARIO VARCHAR(100) ,
FECHA_INS TIMESTAMP
);

DROP TRIGGER IF EXISTS TRG_INSERT_PRODUCTO ;
-- Creacion del trigger
DELIMITER //
CREATE TRIGGER  `TRG_INSERT_PRODUCTO`
AFTER INSERT ON `PRODUCTO`
FOR EACH ROW 
BEGIN
INSERT INTO `AUDIT_PRODUCTO` (NOMBRE_DE_ACCION , NOMBRE_TABLA, ID_PRODUCTO, USUARIO, FECHA_INS)
VALUES ('INSERT', 'PRODUCTO', NEW.ID_PRODUCTO, CURRENT_USER(), NOW());
END//
DELIMITER ;

-- me fijo que la tabla exista
SELECT * FROM AUDIT_PRODUCTO;

-- inserto dato nuevo
INSERT INTO PRODUCTO (NOMBRE_PRODUCTO, DESCRIPCION, STOCK, THUMBNAIL, PRECIO, DUENO_PRODUCTO, ID_CATEGORIA)
VALUES ('Harry potter', 'libro aventura', 10, 'harrypotter.jpg', 500, 9, 5);

-- chequeo la tabla de auditoria otra vez
SELECT * FROM AUDIT_PRODUCTO;


-- ----- ------ ------ ----- ----- ------ ---- ---- ----- ----- ----- ----- 
-- Tabla a la que se le crea el trigger
SELECT * FROM USUARIO;
-- Tabla donde se guarada el resultado del trigger
DROP TABLE IF EXISTS AUDITORIA_USUARIO;
CREATE TABLE IF NOT EXISTS AUDITORIA_USUARIO(
    ID_AUDITORIA INT AUTO_INCREMENT,
    ACCION VARCHAR(10),
    USUARIO_QUE_HIZO_UPDATE VARCHAR(100),
    ID_USER_QUE_SE_MODIFICO INT,
    EMAIL_DEL_UPDATE VARCHAR(50),
    FECHA TIMESTAMP,
    CONSTRAINT PK_USUARIO_AUDITORIA PRIMARY KEY(ID_AUDITORIA)
);

-- Trigger de update en USUARIO
DELIMITER //
CREATE TRIGGER trigger_update_usuario
BEFORE UPDATE ON USUARIO
FOR EACH ROW
BEGIN
    -- Guardar los valores anteriores en la tabla de auditoría antes de la actualización
    INSERT INTO AUDITORIA_USUARIO (ACCION, USUARIO_QUE_HIZO_UPDATE, ID_USER_QUE_SE_MODIFICO, EMAIL_DEL_UPDATE, FECHA)
    VALUES ('UPDATE', CURRENT_USER(), OLD.ID_USER, OLD.EMAIL, NOW());
END //
DELIMITER ;

-- Antes de update
SELECT * FROM USUARIO WHERE ID_USER = 1;

-- UPDATE usuario 1
UPDATE USUARIO
SET APELLIDO = 'Perez', TELEFONO = '555-12345'
WHERE ID_USER = 1;

-- Despues update
SELECT * FROM USUARIO WHERE ID_USER = 1;

-- resultado del trigger
SELECT * FROM AUDITORIA_USUARIO;